language: perl
perl:
  - "5.6.2"
  - "5.8.1"
  - "5.8.4"
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "dev"
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
  allow_failures:
    - perl: dev
before_install:
  - git clone git://github.com/haarg/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -lv $(test-files)
after_success:
  - coverage-report
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
  irc:
    channels:
      - "irc.perl.org#moo-smoke"
    template:
      - "%{branch}#%{build_number} by %{author}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
    skip_join: true
